services:
  - type: web
    name: higher-self-api
    env: node
    buildCommand: npm install --production
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://laughingsmile.netlify.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX
        value: 60
